# Generated by Django 3.2.7 on 2023-12-31 22:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_pins_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pins',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 1, 22, 33, 40, 324208, tzinfo=utc), null=True),
        ),
    ]
