# Generated by Django 3.2.7 on 2024-01-01 00:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20231231_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sfoot',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pins',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 2, 0, 29, 3, 585269, tzinfo=utc), null=True),
        ),
    ]
