# Generated by Django 3.2.7 on 2024-01-04 01:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_auto_20240103_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pins',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 3, 1, 6, 7, 687782, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='dp',
            field=models.ImageField(default='avatar.svg', null=True, upload_to=''),
        ),
    ]
