# Generated by Django 3.2.7 on 2023-12-31 22:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pins',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 1, 22, 9, 28, 487789, tzinfo=utc), null=True),
        ),
    ]
