# Generated by Django 3.2.7 on 2023-12-31 22:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20231231_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pins',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 1, 22, 40, 9, 191021, tzinfo=utc), null=True),
        ),
    ]
