# Generated by Django 3.2.7 on 2024-01-01 00:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20231231_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='dob',
            new_name='birth_date',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='sfoot',
            new_name='stronger_foot',
        ),
        migrations.AlterField(
            model_name='pins',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 2, 0, 38, 27, 650754, tzinfo=utc), null=True),
        ),
    ]
