# Generated by Django 3.2.7 on 2024-01-18 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_auto_20240116_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dp',
            field=models.ImageField(default='avatar.svg', null=True, upload_to=''),
        ),
    ]
