# Generated by Django 3.2.7 on 2024-01-21 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='question',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
