# Generated by Django 3.2.7 on 2024-01-21 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_user_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='question',
        ),
    ]
